### PR TITLE
chore: exclude test files from build

### PR DESCRIPTION
**Pull request by smellai**
### Description of change
With this change, test files will be not included in the build directory

### Pull-Request Checklist

- [ ] Code is up-to-date with the `main` branch
- [ ] `npm run lint` passes with this change
- [ ] `npm run test` passes with this change
- [ ] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [ ] The new commits follow conventions outlined in the [conventional commit spec](https://www.conventionalcommits.org/en/v1.0.0/)

### CODE REVIEW

**Comment by ryansonshine** [comment]
Thanks for the contribution @smellai!

Rather than adding another tsconfig file, what do you think about if we were to update the `files` prop in package.json to only include `lib/src/**/*`?

**Comment by ryansonshine** [comment]
Thanks for the contribution @smellai !

We'll also need to update the `package.json`'s `main` value to point to `./lib/index.js`

**Review by ryansonshine — CHANGES_REQUESTED** [review]
Replace value in `package.json` from:

```json
{
  "main": "./lib/src/index.js",
}
```

to 

```json
{
  "main": "./lib/index.js",
}
```

**Comment by smellai** [comment]
would you like to make this PR eligible for [hacktoberfest](https://hacktoberfest.com/)? (either add the `hacktoberfest` tag to the repositories tags or add the “hacktoberfest-accepted” label to the PRs)

I would like to open a couple of more PRs with small improvements.

**Review by ryansonshine — APPROVED** [review]

**Pull request merged**
